<a href="https://colab.research.google.com/github/wujansin/python_colab/blob/main/Python_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 複習
## 4 basic data type
* int
* float
* str
* bool

## 4 container data type
* list
* tuple
* dict
* set

## 4 standard 語法
* 條件式 if -->選擇性執行程式區塊
* 迴圈  loop -->反覆執行程式區塊
* 函式 function --> 定義好程式區塊，呼叫時候再執行
* 例外處理 exception -->嘗試執行某個程式區塊，如果發生錯誤，就呼叫另一個程式區塊來處理錯誤




# 條件式

In [ ]:
a=2
b=2
if a>b:
    print("a>b")
elif a<b:
    print("a<b")
else:
    print("a=b")    


a=b


## 練習 (BMI計算)
$ bmi = \frac{體重(kg)}{身高(m)} $

|bmi|說明|
|:-:|:-:|
|bmi<18 |過輕|
|18<bmi<24|健康|
|bmi>24|過重|


In [ ]:
weight =48
high =153
bmi = weight/((high/100)**2)
print("BMI=", bmi)
if bmi >24:
    print("過重")
elif bmi>18 and bmi <=24:
    print("標準")
else:
    print("過輕")        


BMI= 20.504933999743688
標準


# 新增區段

In [ ]:
def health(w,h):
    bmi = w/((h/100)**2)
    print("BMI=",bmi)
    if bmi >24:
        return "過重"
    elif bmi>18 and bmi <=24:
        return "標準"
    else:
        return "過輕"

l=health(53,153)
print(l)

BMI= 22.64086462471699
標準


# 迴圈 (Loop)
* for
    * 不只可以用range，還可以用容器型別
* while
    * ex:畫金字塔

## 關於for loop

In [7]:
for i in range(5):
    print(i)

SyntaxError: ignored

In [6]:
x = list("abcdefg")
for i in x:
    print (i)

a
b
c
d
e
f
g


In [10]:
y = {"apple":10, "orange":20, "banana":30}
for i in y.items():
    print(i)
    
for i in y:    
    print(i, "==>", y[i])

('apple', 10)
('orange', 20)
('banana', 30)
apple ==> 10
orange ==> 20
banana ==> 30


# 新增區段

In [3]:
for i in range(5):
    print(' '*(5-i)+ (i*2+1)*'*')

     *
    ***
   *****
  *******
 *********


# 函式 (function)
* 畫金字塔 pyramid(h)

In [2]:
def pyramid(h):
    for i in range(h):
        print(' '*(h-i)+ (i*2+1)*'*') 

pyramid(10)

          *
         ***
        *****
       *******
      *********
     ***********
    *************
   ***************
  *****************
 *******************


# 關於程式區塊

# 例外處理 (Exception Handling)


### f-string

In [12]:
x=1
y=2
print(x, "allan",y)


1 allan 2


In [17]:
print("x={x},y={y}")
print(f"x={x},y={y}")

x={x},y={y}
x=1,y=2


## Exception

In [3]:
def add(x,y):
    print(f"{x}+{y}={x+y}")

def sub(x,y):
    print(f"{x}-{y}={x-y}")

def mul(x,y):
    print(f"{x}*{y}={x*y}")

def div(x,y):
    print(f"{x}/{y}={x/y}")


In [6]:
funcs =[add,sub,div,mul]
x=2
y=0
for func in funcs:
    try:
        func(x,y)
    except Exception as e:
        print(e.args)        


2+0=2
2-0=2
('division by zero',)
2*0=0


* Kaggle 資料科學 網站
* glassdoor 查薪資

# 資料分析簡介
* Numpy ==> Numerical python==>科學運算用
* MatPlotLib ==>Matrix Plot Lib ==>繪圖基礎套件
* Pandas ==> Panel Data ==>資料分析基礎套件

* 套件載入慣用法:
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```



## Numpy
* ndarray --> N-Dim Array
* ufunc --> Universeal Functions


In [ ]:
import numpy as np
x=[1,2,3]
y=[3,4,5]


In [8]:
x+y

[1, 2, 3, 4, 5, 6]

In [9]:
2*x

[1, 2, 3, 1, 2, 3]

In [11]:
list(zip(x,y))

[(1, 4), (2, 5), (3, 6)]

In [20]:
z=[]
for i,j in zip(x,y):
    z.append(i+j)

z

[5, 7, 9]

In [26]:
x1 = np.array(x)
y1 = np.array(y)

2*y1

array([ 8, 10, 12])

In [27]:
x1+y1

array([5, 7, 9])

## What is ufunc

In [28]:
import math
math.sin(math.pi/2)

1.0

In [35]:
np.sin(np.pi/2)

1.0

In [36]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

### 練習題:
請將下列所有資料取平方根(np.sqrt)再乘以10


In [43]:
score = [20,30,36,50,60,50,10,40,70,100]
npscore = np.array(score)
for i in npscore:
    print(math.sqrt(i)*10)

44.721359549995796
54.772255750516614
60.0
70.71067811865476
77.45966692414834
70.71067811865476
31.622776601683796
63.24555320336759
83.66600265340756
100.0


In [46]:
new_score = np.sqrt(npscore)*10
new_score

array([ 44.72135955,  54.77225575,  60.        ,  70.71067812,
        77.45966692,  70.71067812,  31.6227766 ,  63.2455532 ,
        83.66600265, 100.        ])

## ndarray 的index 與 slicing


In [48]:
x= np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
x.dtype

dtype('int64')

In [51]:
x.shape

(25,)

In [55]:
x= x.reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
x.shape

(5, 5)

In [57]:
y = [[ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8,  9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24]]
type(y)       

list

In [58]:
y[2]

[10, 11, 12, 13, 14]

In [59]:
y[2][1:4]

[11, 12, 13]

In [60]:
x[2][1:4]

array([11, 12, 13])

In [62]:
x[2,1:4]

array([11, 12, 13])

In [64]:
x[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [65]:
x[0,:]  #取第0列

array([0, 1, 2, 3, 4])

In [66]:
x[:,0]   #取第0欄

array([ 0,  5, 10, 15, 20])

## Matplotlib
* pyplot
* artist
